version: '3'
services:
  db:
    container_name: web-service-avito-db-1
    image: mysql/mysql-server:5.7
    ports:
      - "${DB_PORT}:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASS}"
      - "MYSQL_DATABASE=${DB_NAME}"   
  web:
    container_name: web-service-avito-web-1
    build: .
    ports:
      - "${SERVER_PORT}:8081"
    volumes:
      - ".:/app"
    depends_on:
      - db
    links:
      - "db:database"